platform :ios, '8.0'
use_frameworks!

target 'DeskAPIClient' do
    pod 'DeskCommon', '~> 1.1'
end

target 'DeskAPIClientTests' do
    pod 'DeskCommonTest', '~> 1.0'
    pod 'Expecta', '~> 0.3.1'
    pod 'OCMock', '~> 3.0.2'
end
