platform :ios, '8.0'

target 'DeskAPIClient' do
    pod 'DeskCommon', '~> 1.0.4'
end

target 'DeskAPIClientTests' do
	pod 'DeskCommonTest', '~> 1.0.2'
    pod 'Expecta', '~> 0.3.1'
    pod 'OCMock', '~> 3.0.2'
    
end
